name: Build

permissions: {}

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      run: rustup update


    - name: Build for Desktop Platforms
      run: cargo build --release
      

  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4


      - name: Set up Rust
        run: rustup update


      - name: Install Android NDK
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/android-ndk-r23b-linux.zip -O ndk.zip
          unzip ndk.zip -d $HOME
          echo "ANDROID_NDK_HOME=$HOME/android-ndk-r23b" >> $GITHUB_ENV
          echo "$HOME/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

      
      - name: Add Android target
        run: rustup target add aarch64-linux-android


      - name: Build for Android
        run: |
          cargo install cross --git https://github.com/cross-rs/cross
          cross build --release --target aarch64-linux-android
          

  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      run: rustup update


    - name: Add iOS target
      run: rustup target add aarch64-apple-ios


    - name: Build for iOS
      run: cargo build --release --target aarch64-apple-ios

